CREATE DATABASE Butor20251014
CHARACTER SET utf8
COLLATE utf8_hungarian_ci;

USE Butor20251014;

CREATE TABLE Telepules(
  IRSZ CHAR(4) PRIMARY KEY,
  Varos VARCHAR(100) NOT NULL
);

CREATE TABLE Vevo(
  VID CHAR(12) PRIMARY KEY,
  Vnev VARCHAR(100) NOT NULL,
  Knev VARCHAR(100) NOT NULL,
  Unev VARCHAR(150)
);

CREATE TABLE Keszlet(
  BID CHAR(12) PRIMARY KEY,
  RID CHAR(12) PRIMARY KEY,
  DB  VARCHAR(100),

  CONSTRAINT Fk_KeszletBID_VasarlasBID,
  FOREIGN KEY (BID) REFERENCES Vasarlas(BID)
);

CREATE TABLE Raktar(
  RID CHAR(12),
  IRSZ CHAR (4),
  Varos VARCHAR(100) NOT NULL,
  KozNev VARCHAR(50) NOT NULL,
  KozJelleg VARCHAR(20) NOT NULL,
  HSZ VARCHAR(10) NOT NULL,
  Emelet VARCHAR (10),
  Ajto VARCHAR(10),

  PRIMARY KEY(RID),
  FOREIGN KEY Raktar(IRSZ) REFERENCES Telepules(IRSZ)
);

CREATE TABLE Tranzakcio(
  RID CHAR(12),
  VID CHAR(12),
  BID CHAR(12),
  DB VARCHAR(100),
  
  PRIMARY KEY(RID, VID, BID),
  FOREIGN KEY (RID) REFERENCES Keszlet(RID),
  FOREIGN KEY (VID) REFERENCES Vevo(VID),
  FOREIGN KEY (BID) REFERENCES Keszlet(BID)
);
