CREATE DATABASE Konyvtar20251009
CHARACTER SET utf8
COLLATE utf8_hungarian_ci;

USE Konyvtar20251009;

CREATE TABLE Konyv(
  ISBN CHAR(12) PRIMARY KEY,
  Cim VARCHAR(150) NOT NULL,
  Kategoria VARCHAR(100) 
);

CREATE TABLE Szerzo(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  Vnev VARCHAR(100) NOT NULL,
  Knev VARCHAR(100) NOT NULL,
  Unev VARCHAR(150)
);

CREATE TABLE Telepulesek(
  IRSZ CHAR(4) PRIMARY KEY,
  Varos VARCHAR(100) NOT NULL
);

CREATE TABLE Konyvmoly(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  Vnev VARCHAR(100) NOT NULL,
  Knev VARCHAR(100) NOT NULL,
  Unev VARCHAR(150)
);

CREATE TABLE Konyvtar(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  TVnev VARCHAR(100) NOT NULL,
  TKnev VARCHAR(100) NOT NULL,
  TUnev VARCHAR(150),
  IRSZ CHAR(4) NOT NULL,
  KozNev VARCHAR(50) NOT NULL,
  KozJelleg VARCHAR(20) NOT NULL,
  HSZ VARCHAR(10) NOT NULL,
  Emelet VARCHAR(10),
  Ajto VARCHAR(10),

  CONSTRAINT FK_KonyvtarIRSZ_TelepulesekIRSZ
  FOREIGN KEY (IRSZ) REFERENCES Telepulesek(IRSZ)
);

CREATE TABLE Keszlet(
  ISBN CHAR(12),
  KonyvtarID INT,
  DB INT NOT NULL,

  PRIMARY KEY (ISBN, KonyvtarID),
  FOREIGN KEY (ISBN) REFERENCES Konyv(ISBN),
  FOREIGN KEY (KonyvtarID) REFERENCES Konyvtar(ID)
);

CREATE TABLE KonyvSzerzo(
  ISBN CHAR(12),
  SzerzoID INT,

  PRIMARY KEY (ISBN, SzerzoID),
  FOREIGN KEY (ISBN) REFERENCES Konyv(ISBN),
  FOREIGN KEY (SzerzoID) REFERENCES Szerzo(ID)
);

CREATE TABLE Tagsag(
  KonyvtarID INT,
  KonyvmolyID INT,

  PRIMARY KEY (KonyvtarID, KonyvmolyID),
  FOREIGN KEY (KonyvtarID) REFERENCES Konyvtar(ID),
  FOREIGN KEY (KonyvmolyID) REFERENCES Konyvmoly(ID)
);